version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"  # Exponer el puerto 8080 en el puerto 8082 del host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mapea el archivo nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
