
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080" # Exponer el puerto 8080 de nginx en el puerto 8082 de tu host volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Solo si tienes un archivo nginx.conf personalizado
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
