version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:80"  # El puerto 80 en NGINX se mapea al 8082 en el host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Asegúrate de que nginx.conf existe en tu proyecto
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
